# webサーバーの設定ファイル
server {
    # 80番ポートで待ち受ける
    listen 80;
    # 指定が無い場合の優先ファイル
    index index.php index.html;
    # サーバー名（ドメイン名）を指定
    server_name localhost;

    # アップロードできるファイルの最大サイズを指定
    client_max_body_size 64M;

    # nginxがファイルを探す基準フォルダ
    root /var/www/public;

    # URLリクエストに対するルール
    location / {
        # 同じ名前のファイルがあるか、フォルダがあるか、どちらも無ければindex.phpに引き継ぐ
        try_files $uri $uri/ /index.php$is_args$args;
    }

    # URLの末尾が.phpで終わる場合のルール
    location ~ \.php$ {
        # php実行が必要ならphpコンテナの9000番ポートに処理を転送する
        # 他は転送に必要な設定値
        fastcgi_split_path_info ^(.+\.php)(/.+)$;
        fastcgi_pass php:9000;
        fastcgi_index index.php;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param PATH_INFO $fastcgi_path_info;
    }
}
