name: Deploy to AWS

# Testsワークフローが終わったら動く（mainブランチのときだけ）
on:
  workflow_run:
    workflows: [Tests]
    types: [completed]
    branches: [main]

# Ubuntu環境で実行(pushの度に使い捨てUbuntu環境が作られる)
jobs:
  deploy:
    # テストが成功したときだけデプロイする
    if: github.event.workflow_run.conclusion == 'success'
    runs-on: ubuntu-latest
    # 上から順番に実行する作業リスト
    steps:
    # リポジトリのクローン
      - uses: actions/checkout@v4
        with:
          # テストが通ったコミットを取得する
          ref: ${{ github.event.workflow_run.head_sha }}
      # Node.jsインストール
      - uses: actions/setup-node@v4
        with:
          node-version: 20

      # srcディレクトリでnpm install実行
      - name: Install dependencies
        working-directory: src
        run: npm install

      # srcディレクトリでnpm run build実行
      - name: Build assets
        working-directory: src
        run: npm run build

      # SSH+git pullでサーバーにコードを反映
      - name: Pull latest code on server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd ~/flea-market-app
            git pull

      # src/public/buildディレクトリをサーバーにアップロード
      - name: Upload built assets
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          source: "src/public/build"
          target: "/home/ubuntu/flea-market-app"
          overwrite: true
